/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcbd",
        "on-primary-fixed": "#001d33",
        "on-tertiary-container": "#4c2c06",
        "tertiary-fixed-dim": "#f0bd8b",
        "surface-container-high": "#222a3d",
        "inverse-on-surface": "#283044",
        "on-primary-container": "#00375a",
        "inverse-primary": "#00629d",
        "on-primary": "#003354",
        "secondary-fixed": "#6bfe9c",
        "tertiary": "#f0bd8b",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed-variant": "#623f18",
        "primary-fixed-dim": "#98cbff",
        "on-surface-variant": "#bec7d4",
        "primary": "#98cbff",
        "inverse-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
        "on-secondary-container": "#00431f",
        "secondary-container": "#06bb63",
        "on-primary-fixed-variant": "#004a77",
        "surface-bright": "#31394d",
        "on-secondary": "#003919",
        "on-surface": "#dae2fd",
        "on-error": "#690005",
        "on-secondary-fixed": "#00210c",
        "surface-variant": "#2d3449",
        "on-error-container": "#ffdad6",
        "surface-tint": "#98cbff",
        "primary-fixed": "#cfe5ff",
        "secondary": "#4ae183",
        "outline-variant": "#3f4852",
        "on-tertiary": "#482904",
        "on-secondary-fixed-variant": "#005228",
        "surface-container-lowest": "#060e20",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#4ae183",
        "on-tertiary-fixed": "#2c1600",
        "on-background": "#dae2fd",
        "primary-container": "#00a3ff",
        "outline": "#88919d",
        "tertiary-container": "#c29364",
        "background": "#0b1326"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "md": "24px",
        "gutter": "24px",
        "xl": "64px",
        "margin-mobile": "16px",
        "lg": "40px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Sora"],
        "data-mono": ["Inter"],
        "headline-lg-mobile": ["Sora"],
        "headline-md": ["Sora"],
        "display-lg": ["Sora"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "data-mono": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
